export const ColorCodes = {
    white: '00',
    black: '01',
    blue: '02',
    green: '03',
    red: '04',
    brown: '05',
    purple: '06',
    orange: '07',
    yellow: '08',
    lightGreen: '09',
    cyan: '10',
    lightCyan: '11',
    lightBlue: '12',
    pink: '13',
    grey: '14',
    lightGrey: '15',
} as const;
